In [1]:
from __future__ import print_function
import torch

In [2]:
torch.version.__version__

'0.4.1'

# PyTorch basics

The torch package contains data structures for multi-dimensional tensors and mathematical operations over these are
defined. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful
utilities.
It has a CUDA counterpart, that enables you to run your tensor computations on an NVIDIA GPU with compute
capability >= 2.0.

In [6]:
x = [12,23,34,45,56,67,78]

In [7]:
torch.is_tensor(x)

False

In [8]:
torch.is_storage(x)

False

In [9]:
y = torch.randn(1,2,3,4,5)

In [10]:
torch.is_tensor(y)

True

In [11]:
torch.is_storage(y)

False

In [12]:
torch.numel(y) # the total number of elements in the input Tensor

120

In [13]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
torch.numel(torch.zeros(4,4))

16

In [15]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [18]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [19]:
type(x)

list

In [20]:
import numpy as np
x1 = np.array(x)

In [21]:
x1

array([12, 23, 34, 45, 56, 67, 78])

In [22]:
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78])

In [20]:
torch.linspace(2, 10, steps=25) #linear spacing

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [23]:
torch.linspace(-10, 10, steps=15)

tensor([-10.0000,  -8.5714,  -7.1429,  -5.7143,  -4.2857,  -2.8571,  -1.4286,
          0.0000,   1.4286,   2.8571,   4.2857,   5.7143,   7.1429,   8.5714,
         10.0000])

In [24]:
torch.logspace(start=-10, end=10, steps=15) #logarithmic spacing

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1968e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

In [25]:
torch.ones(4)

tensor([1., 1., 1., 1.])

In [26]:
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [27]:
# random numbers from a uniform distribution between the values 
# 0 and 1
torch.rand(10)

tensor([0.4518, 0.5653, 0.6348, 0.6437, 0.2143, 0.9604, 0.3669, 0.4934, 0.5334,
        0.1810])

In [28]:
torch.rand(4, 5) 
# random values between 0 and 1 and fillied with a matrix of 
# size rows 4 and columns 5

tensor([[0.3734, 0.0354, 0.0399, 0.4571, 0.8493],
        [0.0460, 0.9193, 0.2551, 0.1654, 0.2708],
        [0.8007, 0.2927, 0.7814, 0.1313, 0.4698],
        [0.1168, 0.0692, 0.7984, 0.0008, 0.9422]])

In [29]:
#random numbers from a normal distribution, 
#with mean =0 and standard deviation =1
torch.randn(10)

tensor([ 0.6038,  0.1653,  0.4317, -1.2466,  0.0525, -1.0223,  0.4983,  0.6985,
         0.1422, -0.5592])

In [30]:
torch.randn(4, 5)

tensor([[ 0.7288,  2.1191,  0.8396,  1.3021, -0.7470],
        [ 0.4583, -0.0548, -0.0256,  0.7262, -0.2352],
        [ 0.4478, -1.0081,  0.2807, -0.7128,  0.2257],
        [-0.6427,  0.7345,  0.3246, -1.6767,  0.2152]])

In [31]:
#selecting values from a range, this is called random permutation
torch.randperm(10)

tensor([6, 4, 1, 0, 2, 9, 8, 7, 5, 3])

In [32]:
#usage of range function 
torch.arange(10, 40,2) #step size 2

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [33]:
torch.arange(10,40) #step size 1

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [34]:
d = torch.randn(4, 5)
d

tensor([[ 0.2959, -2.6443,  0.8257, -0.8048,  1.6426],
        [ 1.2577, -0.5935, -0.5804,  0.1882, -0.0432],
        [-0.4921,  0.2224,  1.0330,  0.4772,  1.2407],
        [-1.2843, -1.3309, -1.1851, -0.4932,  1.4307]])

In [35]:
torch.argmin(d,dim=1)

tensor([1, 1, 0, 1])

In [36]:
torch.argmax(d,dim=1)

tensor([4, 0, 4, 4])

In [37]:
# create a 2dtensor filled with values as 0
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [38]:
# create a 1d tensor filled with values as 0
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
#indexing and performing operation on the tensors
x = torch.randn(4,5)

In [40]:
x

tensor([[ 0.9737, -0.3976, -0.4175, -1.4037, -0.2938],
        [-0.8564,  0.8878,  0.4645, -0.3647,  2.2762],
        [-2.3109, -0.6249, -1.1965, -0.3033,  0.1784],
        [-1.0587,  1.1527, -1.6724,  2.2054, -0.5828]])

In [41]:
#concatenate two tensors
torch.cat((x,x))

tensor([[ 0.9737, -0.3976, -0.4175, -1.4037, -0.2938],
        [-0.8564,  0.8878,  0.4645, -0.3647,  2.2762],
        [-2.3109, -0.6249, -1.1965, -0.3033,  0.1784],
        [-1.0587,  1.1527, -1.6724,  2.2054, -0.5828],
        [ 0.9737, -0.3976, -0.4175, -1.4037, -0.2938],
        [-0.8564,  0.8878,  0.4645, -0.3647,  2.2762],
        [-2.3109, -0.6249, -1.1965, -0.3033,  0.1784],
        [-1.0587,  1.1527, -1.6724,  2.2054, -0.5828]])

In [42]:
#concatenate n times based on array size
torch.cat((x,x,x))

tensor([[ 0.9737, -0.3976, -0.4175, -1.4037, -0.2938],
        [-0.8564,  0.8878,  0.4645, -0.3647,  2.2762],
        [-2.3109, -0.6249, -1.1965, -0.3033,  0.1784],
        [-1.0587,  1.1527, -1.6724,  2.2054, -0.5828],
        [ 0.9737, -0.3976, -0.4175, -1.4037, -0.2938],
        [-0.8564,  0.8878,  0.4645, -0.3647,  2.2762],
        [-2.3109, -0.6249, -1.1965, -0.3033,  0.1784],
        [-1.0587,  1.1527, -1.6724,  2.2054, -0.5828],
        [ 0.9737, -0.3976, -0.4175, -1.4037, -0.2938],
        [-0.8564,  0.8878,  0.4645, -0.3647,  2.2762],
        [-2.3109, -0.6249, -1.1965, -0.3033,  0.1784],
        [-1.0587,  1.1527, -1.6724,  2.2054, -0.5828]])

In [43]:
#concatenate n times based on array size, over column
torch.cat((x,x,x),1)

tensor([[ 0.9737, -0.3976, -0.4175, -1.4037, -0.2938,  0.9737, -0.3976, -0.4175,
         -1.4037, -0.2938,  0.9737, -0.3976, -0.4175, -1.4037, -0.2938],
        [-0.8564,  0.8878,  0.4645, -0.3647,  2.2762, -0.8564,  0.8878,  0.4645,
         -0.3647,  2.2762, -0.8564,  0.8878,  0.4645, -0.3647,  2.2762],
        [-2.3109, -0.6249, -1.1965, -0.3033,  0.1784, -2.3109, -0.6249, -1.1965,
         -0.3033,  0.1784, -2.3109, -0.6249, -1.1965, -0.3033,  0.1784],
        [-1.0587,  1.1527, -1.6724,  2.2054, -0.5828, -1.0587,  1.1527, -1.6724,
          2.2054, -0.5828, -1.0587,  1.1527, -1.6724,  2.2054, -0.5828]])

In [44]:
#concatenate n times based on array size, over rows
torch.cat((x,x),0)

tensor([[ 0.9737, -0.3976, -0.4175, -1.4037, -0.2938],
        [-0.8564,  0.8878,  0.4645, -0.3647,  2.2762],
        [-2.3109, -0.6249, -1.1965, -0.3033,  0.1784],
        [-1.0587,  1.1527, -1.6724,  2.2054, -0.5828],
        [ 0.9737, -0.3976, -0.4175, -1.4037, -0.2938],
        [-0.8564,  0.8878,  0.4645, -0.3647,  2.2762],
        [-2.3109, -0.6249, -1.1965, -0.3033,  0.1784],
        [-1.0587,  1.1527, -1.6724,  2.2054, -0.5828]])

In [45]:
#how to split a tensor among small chunks

In [46]:
help(torch.chunk)

Help on built-in function chunk:

chunk(...)
    chunk(tensor, chunks, dim=0) -> List of Tensors
    
    Splits a tensor into a specific number of chunks.
    
    Last chunk will be smaller if the tensor size along the given dimension
    :attr:`dim` is not divisible by :attr:`chunks`.
    
    Arguments:
        tensor (Tensor): the tensor to split
        chunks (int): number of chunks to return
        dim (int): dimension along which to split the tensor



In [47]:
a = torch.randn(4, 4)
print(a)
torch.chunk(a,2)

tensor([[ 2.4830, -0.9584,  1.5975,  0.0509],
        [ 0.4128, -1.7760, -0.6675, -1.0888],
        [ 0.9758,  0.0496,  0.0805, -0.2817],
        [ 0.0582,  2.5004,  1.0438, -0.6525]])


(tensor([[ 2.4830, -0.9584,  1.5975,  0.0509],
         [ 0.4128, -1.7760, -0.6675, -1.0888]]),
 tensor([[ 0.9758,  0.0496,  0.0805, -0.2817],
         [ 0.0582,  2.5004,  1.0438, -0.6525]]))

In [48]:
torch.chunk(a,2,0)

(tensor([[ 2.4830, -0.9584,  1.5975,  0.0509],
         [ 0.4128, -1.7760, -0.6675, -1.0888]]),
 tensor([[ 0.9758,  0.0496,  0.0805, -0.2817],
         [ 0.0582,  2.5004,  1.0438, -0.6525]]))

In [49]:
torch.chunk(a,2,1)

(tensor([[ 2.4830, -0.9584],
         [ 0.4128, -1.7760],
         [ 0.9758,  0.0496],
         [ 0.0582,  2.5004]]), tensor([[ 1.5975,  0.0509],
         [-0.6675, -1.0888],
         [ 0.0805, -0.2817],
         [ 1.0438, -0.6525]]))

In [50]:
torch.Tensor([[11,12],[23,24]])

tensor([[11., 12.],
        [23., 24.]])

In [51]:
torch.gather(torch.Tensor([[11,12],[23,24]]), 1, 
             torch.LongTensor([[0,0],[1,0]]))

tensor([[11., 11.],
        [24., 23.]])

In [52]:
 torch.LongTensor([[0,0],[1,0]]) 
#the 1D tensor containing the indices to index

tensor([[0, 0],
        [1, 0]])

In [53]:
a = torch.randn(4, 4)
print(a)

tensor([[-0.9605,  0.3085, -1.0552, -0.0221],
        [ 0.9325, -0.5172, -0.0135,  0.6489],
        [ 0.3539, -0.3596, -0.8797,  1.0190],
        [ 0.9964,  0.5531,  0.3831, -0.3234]])


In [54]:
indices = torch.LongTensor([0, 2])

In [55]:
torch.index_select(a, 0, indices)

tensor([[-0.9605,  0.3085, -1.0552, -0.0221],
        [ 0.3539, -0.3596, -0.8797,  1.0190]])

In [56]:
torch.index_select(a, 1, indices)

tensor([[-0.9605, -1.0552],
        [ 0.9325, -0.0135],
        [ 0.3539, -0.8797],
        [ 0.9964,  0.3831]])

In [57]:
#identify null input tensors using nonzero function
torch.nonzero(torch.tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [58]:
torch.nonzero(torch.Tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [59]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),2)

(tensor([12, 21]), tensor([34, 32]), tensor([45, 54]), tensor([56, 65]))

In [58]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),3)

(tensor([12, 21, 34]), tensor([32, 45, 54]), tensor([56, 65]))

In [59]:
torch.zeros(3,2,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [60]:
torch.zeros(3,2,4).size()

torch.Size([3, 2, 4])

In [61]:
#how to reshape the tensors along a new dimension

In [62]:
x

tensor([[-0.2021,  0.9669, -0.9755, -0.3235,  0.7023],
        [-0.2164,  0.3371,  0.3157, -0.6900,  1.2603],
        [ 0.9157,  0.4921, -0.9229,  0.9070,  0.3861],
        [ 1.2092,  0.8473, -0.5978,  0.3835,  0.4785]])

In [63]:
x.t() #transpose is one option to change the shape of the tensor

tensor([[-0.2021, -0.2164,  0.9157,  1.2092],
        [ 0.9669,  0.3371,  0.4921,  0.8473],
        [-0.9755,  0.3157, -0.9229, -0.5978],
        [-0.3235, -0.6900,  0.9070,  0.3835],
        [ 0.7023,  1.2603,  0.3861,  0.4785]])

In [64]:
# transpose partially based on rows and columns

In [65]:
x.transpose(1,0)

tensor([[-0.2021, -0.2164,  0.9157,  1.2092],
        [ 0.9669,  0.3371,  0.4921,  0.8473],
        [-0.9755,  0.3157, -0.9229, -0.5978],
        [-0.3235, -0.6900,  0.9070,  0.3835],
        [ 0.7023,  1.2603,  0.3861,  0.4785]])

In [66]:
# how to remove a dimension from a tensor

In [67]:
x

tensor([[-0.2021,  0.9669, -0.9755, -0.3235,  0.7023],
        [-0.2164,  0.3371,  0.3157, -0.6900,  1.2603],
        [ 0.9157,  0.4921, -0.9229,  0.9070,  0.3861],
        [ 1.2092,  0.8473, -0.5978,  0.3835,  0.4785]])

In [68]:
torch.unbind(x,1) #dim=1 removing a column

(tensor([-0.2021, -0.2164,  0.9157,  1.2092]),
 tensor([0.9669, 0.3371, 0.4921, 0.8473]),
 tensor([-0.9755,  0.3157, -0.9229, -0.5978]),
 tensor([-0.3235, -0.6900,  0.9070,  0.3835]),
 tensor([0.7023, 1.2603, 0.3861, 0.4785]))

In [69]:
torch.unbind(x) #dim=0 removing a row

(tensor([-0.2021,  0.9669, -0.9755, -0.3235,  0.7023]),
 tensor([-0.2164,  0.3371,  0.3157, -0.6900,  1.2603]),
 tensor([ 0.9157,  0.4921, -0.9229,  0.9070,  0.3861]),
 tensor([ 1.2092,  0.8473, -0.5978,  0.3835,  0.4785]))

In [70]:
x

tensor([[-0.2021,  0.9669, -0.9755, -0.3235,  0.7023],
        [-0.2164,  0.3371,  0.3157, -0.6900,  1.2603],
        [ 0.9157,  0.4921, -0.9229,  0.9070,  0.3861],
        [ 1.2092,  0.8473, -0.5978,  0.3835,  0.4785]])

In [71]:
#how to compute the basic mathematrical functions

In [72]:
torch.abs(torch.FloatTensor([-10, -23, 3.000]))

tensor([10., 23.,  3.])

In [73]:
#adding value to the existing tensor, scalar addition
torch.add(x,20)

tensor([[19.7979, 20.9669, 19.0245, 19.6765, 20.7023],
        [19.7836, 20.3371, 20.3157, 19.3100, 21.2603],
        [20.9157, 20.4921, 19.0771, 20.9070, 20.3861],
        [21.2092, 20.8473, 19.4022, 20.3835, 20.4785]])

In [74]:
x

tensor([[-0.2021,  0.9669, -0.9755, -0.3235,  0.7023],
        [-0.2164,  0.3371,  0.3157, -0.6900,  1.2603],
        [ 0.9157,  0.4921, -0.9229,  0.9070,  0.3861],
        [ 1.2092,  0.8473, -0.5978,  0.3835,  0.4785]])

In [75]:
# scalar multiplication
torch.mul(x,2)

tensor([[-0.4043,  1.9337, -1.9509, -0.6470,  1.4047],
        [-0.4327,  0.6743,  0.6314, -1.3800,  2.5205],
        [ 1.8315,  0.9843, -1.8458,  1.8140,  0.7723],
        [ 2.4184,  1.6946, -1.1956,  0.7671,  0.9570]])

In [76]:
x

tensor([[-0.2021,  0.9669, -0.9755, -0.3235,  0.7023],
        [-0.2164,  0.3371,  0.3157, -0.6900,  1.2603],
        [ 0.9157,  0.4921, -0.9229,  0.9070,  0.3861],
        [ 1.2092,  0.8473, -0.5978,  0.3835,  0.4785]])

In [77]:
# how do we represent the equation in the form of a tensor

In [78]:
# y = intercept + (beta * x)

In [79]:
intercept = torch.randn(1)
intercept

tensor([-0.4292])

In [80]:
x = torch.randn(2, 2)
x

tensor([[-0.7945,  0.7653],
        [ 0.5497,  0.8854]])

In [81]:
beta = 0.7456
beta

0.7456

In [82]:
torch.mul(x,beta)

tensor([[-0.5924,  0.5706],
        [ 0.4098,  0.6602]])

In [83]:
torch.add(x,beta,intercept)

tensor([[-1.1145,  0.4453],
        [ 0.2297,  0.5655]])

In [84]:
torch.mul(intercept,x)

tensor([[ 0.3410, -0.3284],
        [-0.2359, -0.3800]])

In [85]:
torch.mul(x,beta)

tensor([[-0.5924,  0.5706],
        [ 0.4098,  0.6602]])

In [86]:
## y = intercept + (beta * x)
torch.add(torch.mul(intercept,x),torch.mul(x,beta)) # tensor y

tensor([[-0.2514,  0.2422],
        [ 0.1739,  0.2802]])

In [87]:
# how to round up tensor values
torch.manual_seed(1234)
torch.randn(5,5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [88]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5,5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [89]:
torch.manual_seed(1234)
torch.floor(torch.randn(5,5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [90]:
# truncate the values in a range say 0,1
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3, max=0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [91]:
#truncate with only lower limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [92]:
#truncate with only upper limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), max=0.3)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.3000],
        [ 0.0000, -2.0000,  0.3000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

In [93]:
#scalar division
torch.div(x,0.10)

tensor([[-7.9450,  7.6528],
        [ 5.4968,  8.8545]])

In [94]:
#compute the exponential of a tensor
torch.exp(x)

tensor([[0.4518, 2.1496],
        [1.7327, 2.4241]])

In [95]:
np.exp(x)

tensor([[0.4518, 2.1496],
        [1.7327, 2.4241]])

In [96]:
#how to get the fractional portion of each tensor

In [97]:
torch.add(x,10)

tensor([[ 9.2055, 10.7653],
        [10.5497, 10.8854]])

In [98]:
torch.frac(torch.add(x,10))

tensor([[0.2055, 0.7653],
        [0.5497, 0.8854]])

In [99]:
# compute the log of the values in a tensor

In [100]:
x

tensor([[-0.7945,  0.7653],
        [ 0.5497,  0.8854]])

In [101]:
torch.log(x) #log of negatives are nan

tensor([[    nan, -0.2675],
        [-0.5984, -0.1217]])

In [102]:
# to rectify the negative values do a power tranforamtion
torch.pow(x,2)

tensor([[0.6312, 0.5857],
        [0.3021, 0.7840]])

In [103]:
# rounding up similar to numpy

In [104]:
x

tensor([[-0.7945,  0.7653],
        [ 0.5497,  0.8854]])

In [105]:
np.round(x)

tensor([[-1.,  1.],
        [ 1.,  1.]])

In [106]:
torch.round(x)

tensor([[-1.,  1.],
        [ 1.,  1.]])

In [107]:
# how to compute the sigmoid of the input tensor

In [108]:
x

tensor([[-0.7945,  0.7653],
        [ 0.5497,  0.8854]])

In [109]:
torch.sigmoid(x)

tensor([[0.3112, 0.6825],
        [0.6341, 0.7080]])

In [110]:
# finding the square root of the values

In [111]:
x

tensor([[-0.7945,  0.7653],
        [ 0.5497,  0.8854]])

In [112]:
torch.sqrt(x)

tensor([[   nan, 0.8748],
        [0.7414, 0.9410]])