In [1]:
import torch

In [2]:
# how to perform random sampling of the tensors

In [3]:
torch.manual_seed(1234)

In [4]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [5]:
#generate random numbers from a statistical distribution

In [6]:
torch.Tensor(4, 4).uniform_(0, 1) #random number from uniform distribution

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [7]:
#now apply the distribution assuming the input values from the 
#tensor are probabilities

In [8]:
torch.bernoulli(torch.Tensor(4, 4).uniform_(0, 1))

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [1., 1., 0., 0.]])

In [9]:
#how to perform sampling from a multinomial distribution

In [10]:
torch.Tensor([10, 10, 13, 10,34,45,65,67,87,89,87,34])

tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.])

In [11]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 
                                34., 45., 65., 67., 
                                87., 89., 87., 34.]), 
                  3)

tensor([ 8,  7, 11])

In [12]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 
                                34., 45., 65., 67., 
                                87., 89., 87., 34.]), 
                  5, replacement=True)

tensor([ 5, 10,  5,  9, 10])

In [13]:
#generate random numbers from the normal distribution

In [14]:
torch.normal(mean=torch.arange(1., 11.), 
             std=torch.arange(1, 0, -0.1))

tensor([1.2111, 2.3034, 3.5310, 4.7278, 6.1060, 6.3294, 6.9060, 7.9908, 9.3492,
        9.9928])

In [15]:
torch.normal(mean=0.5, 
             std=torch.arange(1., 6.))

tensor([-1.1794, -2.9019,  2.4459,  7.5613,  5.9058])

In [16]:
torch.normal(mean=0.5, 
             std=torch.arange(0.2,0.6))

tensor([0.7487])

In [17]:
#computing the descriptive statistics: mean
torch.mean(torch.tensor([10., 10., 13., 10., 34., 
                         45., 65., 67., 87., 89., 87., 34.]))

tensor(45.9167)

In [18]:
# mean across rows and across columns
d = torch.randn(4, 5)
d

tensor([[-0.2632, -0.5432, -1.6406,  0.9295, -1.2777],
        [-0.7428,  0.9711,  0.3551,  0.8562, -0.3635],
        [-0.1552, -1.2282, -0.8039, -0.4530, -0.2217],
        [-2.0901, -1.2658, -1.8761, -0.6066,  0.7470]])

In [19]:
torch.mean(d,dim=0)

tensor([-0.8128, -0.5165, -0.9914,  0.1815, -0.2789])

In [20]:
torch.mean(d,dim=1)

tensor([-0.5590,  0.2152, -0.5724, -1.0183])

In [21]:
#compute median
torch.median(d,dim=0)

(tensor([-0.7428, -1.2282, -1.6406, -0.4530, -0.3635]),
 tensor([1, 2, 0, 2, 1]))

In [22]:
torch.median(d,dim=1)

(tensor([-0.5432,  0.3551, -0.4530, -1.2658]), tensor([1, 2, 3, 1]))

In [23]:
# compute the mode
torch.mode(d)

(tensor([-1.6406, -0.7428, -1.2282, -2.0901]), tensor([2, 0, 1, 0]))

In [24]:
torch.mode(d,dim=0)

(tensor([-2.0901, -1.2658, -1.8761, -0.6066, -1.2777]),
 tensor([3, 3, 3, 3, 0]))

In [25]:
torch.mode(d,dim=1)

(tensor([-1.6406, -0.7428, -1.2282, -2.0901]), tensor([2, 0, 1, 0]))

In [26]:
#compute the standard deviation
torch.std(d)

tensor(0.9237)

In [27]:
torch.std(d,dim=0)

tensor([0.8890, 1.0459, 1.0087, 0.8243, 0.8287])

In [28]:
torch.std(d,dim=1)

tensor([0.9987, 0.7507, 0.4458, 1.1436])

In [29]:
#compute variance
torch.var(d)

tensor(0.8532)

In [30]:
torch.var(d,dim=0)

tensor([0.7903, 1.0939, 1.0175, 0.6795, 0.6868])

In [31]:
torch.var(d,dim=1)

tensor([0.9974, 0.5636, 0.1987, 1.3079])

In [32]:
# compute min and max
torch.min(d)

tensor(-2.0901)

In [33]:
torch.min(d,dim=0)

(tensor([-2.0901, -1.2658, -1.8761, -0.6066, -1.2777]),
 tensor([3, 3, 3, 3, 0]))

In [34]:
torch.min(d,dim=1)

(tensor([-1.6406, -0.7428, -1.2282, -2.0901]), tensor([2, 0, 1, 0]))

In [35]:
torch.max(d)

tensor(0.9711)

In [36]:
torch.max(d,dim=0)

(tensor([-0.1552,  0.9711,  0.3551,  0.9295,  0.7470]),
 tensor([2, 1, 1, 0, 3]))

In [37]:
torch.max(d,dim=1)

(tensor([ 0.9295,  0.9711, -0.1552,  0.7470]), tensor([3, 1, 0, 4]))

In [38]:
# sorting a tensor
torch.sort(d)

(tensor([[-1.6406, -1.2777, -0.5432, -0.2632,  0.9295],
         [-0.7428, -0.3635,  0.3551,  0.8562,  0.9711],
         [-1.2282, -0.8039, -0.4530, -0.2217, -0.1552],
         [-2.0901, -1.8761, -1.2658, -0.6066,  0.7470]]),
 tensor([[2, 4, 1, 0, 3],
         [0, 4, 2, 3, 1],
         [1, 2, 3, 4, 0],
         [0, 2, 1, 3, 4]]))

In [39]:
torch.sort(d,dim=0)

(tensor([[-2.0901, -1.2658, -1.8761, -0.6066, -1.2777],
         [-0.7428, -1.2282, -1.6406, -0.4530, -0.3635],
         [-0.2632, -0.5432, -0.8039,  0.8562, -0.2217],
         [-0.1552,  0.9711,  0.3551,  0.9295,  0.7470]]),
 tensor([[3, 3, 3, 3, 0],
         [1, 2, 0, 2, 1],
         [0, 0, 2, 1, 2],
         [2, 1, 1, 0, 3]]))

In [40]:
torch.sort(d,dim=0,descending=True)

(tensor([[-0.1552,  0.9711,  0.3551,  0.9295,  0.7470],
         [-0.2632, -0.5432, -0.8039,  0.8562, -0.2217],
         [-0.7428, -1.2282, -1.6406, -0.4530, -0.3635],
         [-2.0901, -1.2658, -1.8761, -0.6066, -1.2777]]),
 tensor([[2, 1, 1, 0, 3],
         [0, 0, 2, 1, 2],
         [1, 2, 0, 2, 1],
         [3, 3, 3, 3, 0]]))

In [41]:
torch.sort(d,dim=1,descending=True)

(tensor([[ 0.9295, -0.2632, -0.5432, -1.2777, -1.6406],
         [ 0.9711,  0.8562,  0.3551, -0.3635, -0.7428],
         [-0.1552, -0.2217, -0.4530, -0.8039, -1.2282],
         [ 0.7470, -0.6066, -1.2658, -1.8761, -2.0901]]),
 tensor([[3, 0, 1, 4, 2],
         [1, 3, 2, 4, 0],
         [0, 4, 3, 2, 1],
         [4, 3, 1, 2, 0]]))

In [42]:
from torch.autograd import Variable

In [43]:
Variable(torch.ones(2,2),requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [44]:
a, b = 12,23
x1 = Variable(torch.randn(a,b),
            requires_grad=True)
x2 = Variable(torch.randn(a,b),
            requires_grad=True)
x3 =Variable(torch.randn(a,b),
            requires_grad=True)

In [45]:
c = x1 * x2
d = a + x3
e = torch.sum(d)

e.backward()

print(e)

tensor(3303.0298, grad_fn=<SumBackward0>)


In [46]:
x1.data

tensor([[ 0.3474,  0.2856, -0.0495,  0.6225,  0.1657,  0.3158,  0.2492, -0.4978,
         -0.0170, -0.2830, -0.6446, -0.0199,  1.6222,  1.4239,  0.9069,  0.0763,
          0.3422, -0.2873, -0.6726,  0.8843, -0.6659, -0.7335, -0.2760],
        [ 0.5549, -0.0609,  2.1073, -0.9930,  1.4080,  0.2597,  0.8076, -1.2618,
         -0.7711,  1.3940,  0.6060,  0.2209, -0.8245, -0.0256, -1.9850, -0.3788,
         -1.5030, -0.0175, -0.9194, -0.9389, -1.9421,  0.9805, -0.0745],
        [-0.7118,  1.6136, -0.9792,  0.8285, -0.2501,  0.1602,  0.2078,  1.1879,
         -0.7320,  1.3668,  0.9069,  1.5691, -0.1108, -0.2573,  0.6365, -0.4852,
         -0.7144, -0.0600,  0.1858, -0.1704,  1.0270,  0.0704,  0.4298],
        [ 0.8205, -1.4562,  0.3013, -0.2252,  0.1193, -1.0772,  0.2516,  0.0669,
          1.4607,  0.7712,  0.0012,  0.3775,  0.7332, -0.4915, -1.1049,  0.1970,
         -0.1435,  1.4660, -0.1042, -1.0545, -0.1973,  0.8522, -0.4066],
        [-1.2096,  0.0365,  0.8257, -0.6476, -0.5563, -0.650

In [47]:
x2.data

tensor([[-0.5864, -0.0455, -0.7560, -1.1689, -0.9389,  0.8857,  1.3764, -0.7828,
          0.1678,  0.2797, -0.6915, -0.5131,  1.1427, -1.0126,  0.1160, -1.0350,
         -0.6508, -0.0779, -0.0912,  0.5024, -0.4517, -0.4807,  0.5907],
        [ 0.1634, -0.2600,  1.6992, -2.1036, -1.8971,  1.4661,  0.6120,  0.7994,
          0.9301,  0.2647, -0.4921,  0.3055,  0.5843, -2.1502,  0.4151,  0.0032,
         -0.3858, -0.7181, -1.8785, -0.2401, -1.3253,  1.1415, -0.4416],
        [ 0.3492, -1.6730,  0.5750,  0.3497,  1.1152, -0.5058,  0.1733, -0.6813,
          0.0256,  1.2838, -0.3343, -1.3312,  1.3023, -1.4379, -1.7115, -0.8005,
          1.4921, -0.1077, -0.0295, -0.2446, -0.5917,  0.0851,  0.0752],
        [ 0.8398,  1.3866, -0.9521,  0.5690, -0.3689,  1.3491,  1.5738,  1.2403,
          0.8706, -0.7415,  1.7150,  0.9138,  1.1533,  0.5870,  1.7935, -0.4375,
         -0.4464, -0.7372,  0.0616,  0.2363,  0.0920, -0.1961, -0.5081],
        [-0.8078,  1.6439, -1.2366,  0.0595, -0.1920,  1.010

In [48]:
x3.data

tensor([[ 0.4955, -0.7306,  0.2499,  0.2458,  0.1029, -0.6494, -0.3258,  0.8149,
          0.5885,  1.6232,  0.4841,  0.3293, -1.2471,  0.2117,  1.4315,  0.0502,
          0.9736,  0.0087, -0.7901,  0.0267, -0.3120,  2.4534,  0.7926],
        [ 0.2382,  1.8277,  0.6758, -2.0323, -0.3952,  0.7286,  1.3579,  1.3583,
         -0.5818, -1.3091,  1.5569, -1.4629,  0.6109,  0.2401, -0.5455,  2.9154,
         -0.1985, -0.2369,  0.1182, -0.8322,  0.1364,  0.4531, -0.1112],
        [ 1.0307, -1.1862,  0.3823,  0.0338,  0.9814, -1.9638, -0.2218,  0.1477,
         -0.1875,  0.9963, -1.9271,  0.8275,  1.7371, -0.7392, -0.1709,  1.2120,
          0.9385,  0.3245, -1.6697, -0.5777, -1.4787, -0.2400,  0.4558],
        [-1.0911,  0.1566, -1.0629,  0.5193,  0.4776, -0.7194,  0.3499, -0.3935,
         -0.3622, -3.4058, -0.1108,  1.2183,  0.2079, -0.0961, -0.6697, -0.1985,
         -1.1560, -0.7709, -0.4655,  1.6369, -0.6030, -0.7429, -0.5210],
        [-0.8078, -0.4448,  1.4265,  0.2566,  0.9585,  0.126

In [102]:
from torch import FloatTensor
from torch.autograd import Variable

a = Variable(FloatTensor([5]))

weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (12, 53, 91, 73)]

w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
Loss = (10 - d)

Loss.backward()

for index, weight in enumerate(weights, start=1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to Loss: {gradient}")

Gradient of w1 w.r.t to Loss: -455.0
Gradient of w2 w.r.t to Loss: -365.0
Gradient of w3 w.r.t to Loss: -60.0
Gradient of w4 w.r.t to Loss: -265.0


In [50]:
# Using forward pass
def forward(x):
    return x * w

In [51]:
import torch
from torch.autograd import Variable

x_data = [11.0, 22.0, 33.0]
y_data = [21.0, 14.0, 64.0]

w = Variable(torch.Tensor([1.0]),  requires_grad=True)  # Any random value

# Before training
print("predict (before training)",  4, forward(4).data[0])

predict (before training) 4 tensor(4.)


In [52]:
# define the Loss function
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

In [53]:
# Run the Training loop
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data

        # Manually set the gradients to zero after updating weights
        w.grad.data.zero_()

    print("progress:", epoch, l.data[0])

	grad:  11.0 21.0 tensor(-220.)
	grad:  22.0 14.0 tensor(2481.6001)
	grad:  33.0 64.0 tensor(-51303.6484)
progress: 0 tensor(604238.8125)
	grad:  11.0 21.0 tensor(118461.7578)
	grad:  22.0 14.0 tensor(-671630.6875)
	grad:  33.0 64.0 tensor(13114108.)
progress: 1 tensor(39481139200.)
	grad:  11.0 21.0 tensor(-30279010.)
	grad:  22.0 14.0 tensor(171986000.)
	grad:  33.0 64.0 tensor(-3358889472.)
progress: 2 tensor(2590022582665216.)
	grad:  11.0 21.0 tensor(7755301376.)
	grad:  22.0 14.0 tensor(-44050112512.)
	grad:  33.0 64.0 tensor(860298674176.)
progress: 3 tensor(169906757784039325696.)
	grad:  11.0 21.0 tensor(-1986333900800.)
	grad:  22.0 14.0 tensor(11282376818688.)
	grad:  33.0 64.0 tensor(-220344807849984.)
progress: 4 tensor(11145967797036089329319936.)
	grad:  11.0 21.0 tensor(508751660449792.)
	grad:  22.0 14.0 tensor(-2889709562888192.)
	grad:  33.0 64.0 tensor(56436029183229952.)
progress: 5 tensor(731181229735636676902291243008.)
	grad:  11.0 21.0 tensor(-13030450598720307

In [54]:
# After training
print("predict (after training)",  4, forward(4).data[0])

predict (after training) 4 tensor(-9268691075357861748932608.)


In [55]:
z = Variable(torch.Tensor(4, 4).uniform_(-5, 5))
print(z)

tensor([[-0.7270,  4.2119, -0.3071, -3.6691],
        [-2.8417, -1.1818, -1.4654, -0.4344],
        [-2.0130, -2.3842,  1.3962,  1.4962],
        [-2.0996,  1.8881, -1.9797,  0.2337]])


In [56]:
print('Requires Gradient : %s ' % (z.requires_grad))
print('Volatile : %s ' % (z.volatile))
print('Gradient : %s ' % (z.grad))
print(z.data)

Requires Gradient : False 
Volatile : False 
Gradient : None 
tensor([[-0.7270,  4.2119, -0.3071, -3.6691],
        [-2.8417, -1.1818, -1.4654, -0.4344],
        [-2.0130, -2.3842,  1.3962,  1.4962],
        [-2.0996,  1.8881, -1.9797,  0.2337]])


/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: volatile was removed (Variable.volatile is always False)
  


In [83]:
x = Variable(torch.Tensor(4, 4).uniform_(-4, 5))
y = Variable(torch.Tensor(4, 4).uniform_(-3, 2))
# matrix multiplication
z = torch.mm(x, y)
print(z.size())

torch.Size([4, 4])


In [84]:
x.data

tensor([[-2.4582, -3.9389,  2.6662,  0.5629],
        [ 4.2173, -1.1122, -3.8421, -1.9672],
        [-2.5722, -0.3963, -3.4676,  2.3133],
        [ 3.7414,  0.6285, -3.9795,  2.0648]])

In [103]:
#tensor operations

In [109]:
mat1 = torch.FloatTensor(4,4).uniform_(0,1)
mat1

tensor([[0.7748, 0.5287, 0.8794, 0.0527],
        [0.2824, 0.0036, 0.4439, 0.1425],
        [0.7889, 0.8024, 0.2917, 0.9638],
        [0.1534, 0.1216, 0.4023, 0.6097]])

In [110]:
mat2 = torch.FloatTensor(5,4).uniform_(0,1)
mat2

tensor([[0.9493, 0.1600, 0.8915, 0.7011],
        [0.2557, 0.1726, 0.6665, 0.4602],
        [0.9003, 0.5600, 0.0388, 0.3431],
        [0.3064, 0.2131, 0.4333, 0.7120],
        [0.1883, 0.4072, 0.2834, 0.8132]])

In [111]:
vec1 = torch.FloatTensor(4).uniform_(0,1)
vec1

tensor([0.8854, 0.9122, 0.9897, 0.2618])

In [112]:
# scalar addition

In [113]:
mat1 + 10.5

tensor([[11.2748, 11.0287, 11.3794, 10.5527],
        [10.7824, 10.5036, 10.9439, 10.6425],
        [11.2889, 11.3024, 10.7917, 11.4638],
        [10.6534, 10.6216, 10.9023, 11.1097]])

In [114]:
# scalar subtraction

In [115]:
mat2 - 0.20

tensor([[ 0.7493, -0.0400,  0.6915,  0.5011],
        [ 0.0557, -0.0274,  0.4665,  0.2602],
        [ 0.7003,  0.3600, -0.1612,  0.1431],
        [ 0.1064,  0.0131,  0.2333,  0.5120],
        [-0.0117,  0.2072,  0.0834,  0.6132]])

In [116]:
# vector and matrix addition

In [117]:
mat1 + vec1

tensor([[1.6603, 1.4409, 1.8691, 0.3145],
        [1.1678, 0.9158, 1.4336, 0.4042],
        [1.6743, 1.7145, 1.2814, 1.2255],
        [1.0388, 1.0337, 1.3920, 0.8715]])

In [118]:
mat2 + vec1

tensor([[1.8348, 1.0722, 1.8812, 0.9629],
        [1.1412, 1.0848, 1.6562, 0.7220],
        [1.7857, 1.4721, 1.0285, 0.6049],
        [1.1918, 1.1252, 1.4230, 0.9738],
        [1.0738, 1.3193, 1.2731, 1.0750]])

In [119]:
# matrix-matrix addition

In [123]:
mat1 + mat2

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 0

In [131]:
mat1 * mat1

tensor([[0.6004, 0.2795, 0.7733, 0.0028],
        [0.0797, 0.0000, 0.1970, 0.0203],
        [0.6224, 0.6438, 0.0851, 0.9288],
        [0.0235, 0.0148, 0.1618, 0.3717]])

In [ ]:
# about Bernoulli distribution

In [138]:
from torch.distributions.bernoulli import Bernoulli

In [139]:
dist = Bernoulli(torch.tensor([0.3,0.6,0.9]))

In [140]:
dist.sample() #sample is binary, it takes 1 with p and 0 with 1-p

tensor([1., 1., 1.])

In [132]:
#Creates a Bernoulli distribution parameterized by probs 
#Samples are binary (0 or 1). They take the value 1 with probability p 
#and 0 with probability 1 - p.

In [133]:
from torch.distributions.beta import Beta

In [141]:
dist = Beta(torch.tensor([0.5]), torch.tensor([0.5]))
dist

Beta()

In [142]:
dist.sample()

tensor([0.3067])

In [143]:
from torch.distributions.binomial import Binomial

In [144]:
dist = Binomial(100, torch.tensor([0 , .2, .8, 1]))

In [147]:
dist.sample()

tensor([  0.,  29.,  85., 100.])

In [148]:
# 100- count of trials
# 0, 0.2, 0.8 and 1 are event probabilities

In [174]:
from torch.distributions.categorical import Categorical

In [175]:
dist = Categorical(torch.tensor([ 0.20, 0.20, 0.20, 0.20, 0.20 ]))
dist

Categorical()

In [176]:
dist.sample()

tensor(4)

In [177]:
# 0.20, 0.20, 0.20, 0.20,0.20 event probabilities

In [155]:
# Laplace distribution parameterized by loc and ‘scale’.

In [157]:
from torch.distributions.laplace import Laplace

In [161]:
dist = Laplace(torch.tensor([10.0]), torch.tensor([0.990]))
dist

Laplace()

In [162]:
dist.sample()

tensor([10.2167])

In [163]:
#Normal (Gaussian) distribution parameterized by loc and ‘scale’.

In [165]:
from torch.distributions.normal import Normal

In [166]:
dist = Normal(torch.tensor([100.0]), torch.tensor([10.0]))
dist

Normal()

In [167]:
dist.sample()

tensor([95.2452])